### ISSUE TITLE
Uniqueness of files, directories, etc.

### ISSUE THREAD

**Issue by spl** [75lb/file-set#5]
I'm looking for a library that does what `file-set` appears to do, but I just wanted to confirm something first.

Are your `fileSet.files`, `fileSet.dirs`, and `fileSet.notExisting` arrays composed of _unique_ elements (i.e. without duplicates)?

The use of “set” in the package name and [`indexOf`][indexOf] seem to imply that the answer to the question is “yes.” But, since I didn't see anything mentioned in the documentation, I wanted to first confirm it. If true, would you mind, just to be explicit, noting it in the `README.md`?

Thanks in advance!

[indexOf]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by 75lb** [comment]
Yes, no duplicates.. i added some [specific test coverage to demonstrate](https://github.com/75lb/file-set/blob/master/test/test.js#L41).

**Comment by spl** [comment]
Thanks!

To save inquisitive future people like me some time, would you please add a note or two that mention keywords like “unique” or “duplicates” somewhere?

**Comment by 75lb** [comment]
done, thanks for the feedback 👍
